version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: football-postgres
    environment:
      POSTGRES_DB: football_data
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_pass
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U football_user -d football_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: football-backend
    ports:
      - "127.0.0.1:6000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./football-open/data:/app/football-open/data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://fudbal.vukodev.com/api}
    container_name: football-frontend
    ports:
      - "127.0.0.1:6001:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:

