CREATE INDEX "idx_competitions_country" ON "competitions" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_competitions_gender" ON "competitions" USING btree ("competition_gender");--> statement-breakpoint
CREATE INDEX "idx_seasons_competition" ON "seasons" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "idx_events_match" ON "events" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "idx_events_type" ON "events" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX "idx_events_player" ON "events" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_events_team" ON "events" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_events_period_minute" ON "events" USING btree ("period","minute");--> statement-breakpoint
CREATE INDEX "idx_events_possession" ON "events" USING btree ("possession");--> statement-breakpoint
CREATE INDEX "idx_events_match_index" ON "events" USING btree ("match_id","index");--> statement-breakpoint
CREATE INDEX "idx_player_cards_match" ON "player_cards" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "idx_player_cards_player" ON "player_cards" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_player_cards_type" ON "player_cards" USING btree ("card_type");--> statement-breakpoint
CREATE INDEX "idx_player_lineups_match" ON "player_lineups" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "idx_player_lineups_player" ON "player_lineups" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_player_lineups_team" ON "player_lineups" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_player_lineups_country" ON "player_lineups" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_player_positions_match" ON "player_positions" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "idx_player_positions_player" ON "player_positions" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "idx_player_positions_position" ON "player_positions" USING btree ("position_id");--> statement-breakpoint
CREATE INDEX "idx_managers_country" ON "managers" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_match_managers_match" ON "match_managers" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "idx_match_managers_manager" ON "match_managers" USING btree ("manager_id");--> statement-breakpoint
CREATE INDEX "idx_match_managers_team" ON "match_managers" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX "idx_matches_competition" ON "matches" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "idx_matches_season" ON "matches" USING btree ("competition_id","season_id");--> statement-breakpoint
CREATE INDEX "idx_matches_date" ON "matches" USING btree ("match_date");--> statement-breakpoint
CREATE INDEX "idx_matches_home_team" ON "matches" USING btree ("home_team_id");--> statement-breakpoint
CREATE INDEX "idx_matches_away_team" ON "matches" USING btree ("away_team_id");--> statement-breakpoint
CREATE INDEX "idx_matches_stadium" ON "matches" USING btree ("stadium_id");--> statement-breakpoint
CREATE INDEX "idx_matches_referee" ON "matches" USING btree ("referee_id");--> statement-breakpoint
CREATE INDEX "idx_matches_stage" ON "matches" USING btree ("competition_stage_id");--> statement-breakpoint
CREATE INDEX "idx_referees_country" ON "referees" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_stadiums_country" ON "stadiums" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_teams_country" ON "teams" USING btree ("country_id");--> statement-breakpoint
CREATE INDEX "idx_teams_gender" ON "teams" USING btree ("team_gender");